name: Deploy to WordPress.org

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to WordPress.org SVN
    runs-on: ubuntu-latest
    if: github.repository_owner == '{{github_org}}'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build production assets
      run: npm run build:production

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: {{theme_slug}}
        VERSION: ${{ github.event.release.tag_name }}